version: '3.2'

services:
    fpm:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                PHP_VERSION: '7.4'
                APP_NAME: 'app'
        volumes:
            - ~/.composer:/home/docker/.composer
        environment:
            COMPOSER_HOME: /home/docker/.composer
            PHP_IDE_CONFIG: 'serverName=symfony'
            XDEBUG_CONFIG: >-
                client_host=172.17.0.1
                idekey=PHPSTORM
            XDEBUG_ENABLED: '${XDEBUG_ENABLED:-0}'
            XDEBUG_SESSION: 1
        stdin_open: true
        tty: true

